package postgres

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/jackc/pgx/v5/stdlib"
	"github.com/pressly/goose/v3"
	"hookline/migrations"
)

const migrationLockID int64 = 4815162342

// Migrate applies embedded Goose migrations while holding a PostgreSQL
// advisory lock. It also adopts databases created by Hookline's legacy
// migration runner without replaying already-applied migrations.
func Migrate(ctx context.Context, pool *pgxpool.Pool) error {
	lock, err := pool.Acquire(ctx)
	if err != nil {
		return fmt.Errorf("acquire migration lock connection: %w", err)
	}
	defer lock.Release()
	if _, err = lock.Exec(ctx, `SELECT pg_advisory_lock($1)`, migrationLockID); err != nil {
		return fmt.Errorf("lock migrations: %w", err)
	}
	defer func() { _, _ = lock.Exec(context.Background(), `SELECT pg_advisory_unlock($1)`, migrationLockID) }()

	db := stdlib.OpenDBFromPool(pool)
	defer func() { _ = db.Close() }()
	if err = bridgeLegacyMigrations(ctx, db); err != nil {
		return err
	}
	goose.SetBaseFS(migrations.FS)
	if err = goose.SetDialect("postgres"); err != nil {
		return fmt.Errorf("configure goose: %w", err)
	}
	if err = goose.UpContext(ctx, db, "."); err != nil {
		return fmt.Errorf("apply migrations: %w", err)
	}
	return nil
}

func bridgeLegacyMigrations(ctx context.Context, db *sql.DB) error {
	var legacyExists, gooseExists bool
	if err := db.QueryRowContext(ctx, `SELECT to_regclass('hookline_schema_migrations') IS NOT NULL, to_regclass('goose_db_version') IS NOT NULL`).Scan(&legacyExists, &gooseExists); err != nil {
		return fmt.Errorf("inspect migration metadata: %w", err)
	}
	if !legacyExists || gooseExists {
		return nil
	}
	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("begin legacy migration bridge: %w", err)
	}
	defer func() { _ = tx.Rollback() }()
	if _, err = tx.ExecContext(ctx, `CREATE TABLE goose_db_version (
		id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		version_id bigint NOT NULL,
		is_applied boolean NOT NULL,
		tstamp timestamp NOT NULL DEFAULT now()
	)`); err != nil {
		return fmt.Errorf("create goose metadata: %w", err)
	}
	if _, err = tx.ExecContext(ctx, `INSERT INTO goose_db_version(version_id,is_applied) VALUES(0,true)`); err != nil {
		return fmt.Errorf("initialize goose metadata: %w", err)
	}
	if _, err = tx.ExecContext(ctx, `INSERT INTO goose_db_version(version_id,is_applied)
		SELECT version,true FROM hookline_schema_migrations ORDER BY version`); err != nil {
		return fmt.Errorf("copy legacy migration versions: %w", err)
	}
	if err = tx.Commit(); err != nil {
		return fmt.Errorf("commit legacy migration bridge: %w", err)
	}
	return nil
}
